### ISSUE TITLE
No rejection/acception indication

### ISSUE THREAD

**Issue by getkirill** [dipix-empire/dipix-bot-v2#3]
rejecting join form doesn't ring any bells.

**Comment by Philainel** [comment]
I think we also do join requests public

**Comment by Philainel** [comment]
we'll keep requests private and bot'll be able to open private dialogues ( Issue #5 )

**Comment by Philainel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Acception / Rejection indication](https://trello.com/c/DOHzja2W/3-acception-rejection-indication)

**Comment by Philainel** [comment]
Implemented in 0060372

**Comment by Philainel** [comment]
Implemented in 0060372..dd5ae7a

**Comment by getkirill** [comment]
> Implemented in [dd5ae7a](https://github.com/dipix-empire/dipix-bot-v2/commit/dd5ae7a0294ecfd377596f8164f44ef1a548f335)

forgor to close
