### ISSUE TITLE
Error while notify user about balance update

### ISSUE THREAD

**Issue by Philainel** [dipix-empire/dipix-bot-v2#4]
Error when admin changing user balance. Balance changing but no notification to the user.

**Comment by Philainel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Error while notify user about balance update](https://trello.com/c/0rkswCAr/4-error-while-notify-user-about-balance-update)

**Comment by Philainel** [comment]
Solved with 2a9c94b

**Comment by getkirill** [comment]
> Solved with [2a9c94b](https://github.com/dipix-empire/dipix-bot-v2/commit/2a9c94b79c42e899518f4aae6ed8409e0749ab4b)

forgor to close as completed
